import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { resolveWorkspace } from '../src/host/adapter.js';
import { planProjectMigration } from '../src/migration.js';
import { MemoryService } from '../src/service.js';
import { UnifiedStore } from '../src/store.js';
import { digest } from '../src/domain.js';
import { FixtureModels } from '../scripts/fixture-models.js';

test('repository subdirectories and linked worktrees resolve to one project while preserving host boundaries', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'banana-project-root-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const main = join(directory, 'main'), linked = join(directory, 'linked');
  await mkdir(main); await mkdir(join(main, 'src'));
  execFileSync('git', ['init', '-q', main]);
  execFileSync('git', ['-C', main, '-c', 'user.name=Test Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-q', '--allow-empty', '-m', 'Fixture']);
  execFileSync('git', ['-C', main, 'worktree', 'add', '-q', '--detach', linked]);
  const root = await resolveWorkspace(main), child = await resolveWorkspace(join(main, 'src')), worktree = await resolveWorkspace(linked);
  assert.equal(child.projectRoot, root.workspace); assert.equal(worktree.projectRoot, root.workspace);
  assert.notEqual(worktree.workspace, root.workspace);
});

test('explicit migration preserves IDs, source lineage, candidate status, recall and deletion across restart', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'banana-migrate-'));
  const workspace = join(directory, 'project'); await mkdir(workspace);
  const canonical = (await resolveWorkspace(workspace)).workspace!;
  t.after(() => rm(directory, { recursive: true, force: true }));
  const text = 'MIGRATED_CACHE 使用独立缓存。';
  const models = new FixtureModels([{ text, type: 'fact', conditions: [] }]);
  let service = await MemoryService.open(directory, { models });
  const first = await service.bind({ workspace: null, sessionId: 'one', origin: 'mcp', includeCandidates: true });
  const second = await service.bind({ workspace: null, sessionId: 'two', origin: 'mcp', includeCandidates: true });
  await service.record(first, { id: 'first', text, projectName: 'Same name' });
  await service.record(second, { id: 'second', text, projectName: 'Same name' });
  await service.processPending();
  const before = await service.dashboard() as any;
  await service.close();
  const store = await UnifiedStore.open(join(directory, 'memory.lance'));
  const rows = await store.all();
  const mapping = [{ projectIds: [first.projectId, second.projectId], workspace, name: 'Canonical project' }];
  const plan = await planProjectMigration(rows, mapping);
  assert.equal((await store.all('project')).length, 2, 'preview does not write');
  await assert.rejects(planProjectMigration(rows, [...mapping, ...mapping]), /duplicate_migration/);
  await store.commit(plan);
  assert.deepEqual(await planProjectMigration(await store.all(), mapping), [], 'migration is idempotent');
  await store.close();
  service = await MemoryService.open(directory, { models });
  t.after(() => service.close());
  const after = await service.dashboard() as any;
  assert.equal(after.totals.projects, 1); assert.equal(after.totals.memories, 2); assert.equal(after.totals.active, 0);
  assert.deepEqual(after.memories.map((row: any) => row.id).sort(), before.memories.map((row: any) => row.id).sort());
  const next = await service.bind({ workspace: canonical, sessionId: 'new', origin: 'mcp', includeCandidates: true });
  assert.equal(next.projectId, 'p:' + digest(canonical));
  assert.equal((await service.recall(next, 'MIGRATED_CACHE')).memories.length, 2);
  const host = await service.bind({ workspace: canonical, sessionId: 'host', origin: 'hook' });
  const memory = after.memories[0];
  const preview = await service.manage(host, (await service.issueIntent(host, { action: 'delete-preview', target: memory.id, expectedVersion: memory.version })).intentToken);
  await service.manage(host, (await service.issueIntent(host, { action: 'delete', previewId: preview.previewId })).intentToken);
  assert.equal((await service.dashboard() as any).totals.memories, 1);
});
